/*
 * @Author: wumingyue
 * @Date: 2024-12-19 15:26:42
 * @Desc: 
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "./components/header";
import "./globals.css";
import Link from "@/node_modules/next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  team,
  analytics
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <AntdRegistry>


          <div>
            <div>
              <Link href='/'>Home</Link>
              <Link href='/visitors'>Visitors</Link>
            </div>
            <div>
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>

      </body>
    </html>
  );
}
